import { PropsWithChildren, ReactNode } from "react";
import { GlobalContextProvider } from "./contexts/GlobalContext";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: PropsWithChildren<ReactNode>;
}) {
  return (
    <html lang="en">
      <body style={{ padding: "0px", margin: "0px" }}>
        <GlobalContextProvider>{children}</GlobalContextProvider>
      </body>
    </html>
  );
}
